image: node:12.14.1

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: .pre
  script:
    - cd code
    - npm install

build_code:
  stage: build
  script:
    - ls
    - cd code
    - npm install
    - npm run build

run_cypress:
  stage: test
  script:
    - npm run serve
    - npm run cypress:run
