image: node:12.14.1

stages:
  - test
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: .pre
  script:
    - cd code
    - npm install

run_cypress:
  stage: test
  script:
    - cd code
    - npm install
    - wait-on http://localhost:8080 && npm run cypress:run
    - npm run serve
    - ls

build_code:
  stage: build
  script:
    - ls
    - cd code
    - npm install
    - npm run build
