image: node:12.14.1

stages:
  - test
  - build

cache:
  paths:
    - node_modules/

# install_dependencies:
#   stage: .pre
#   script:
#     - cd code
#     - npm install

run_cypress:
  stage: test
  script:
    - cd code
    # - apt-get -y install xvfb
    - apt update -f
    # - apt upgrade
    - apt-get install python-pip -f
    - apt-get install xvfb xserver-xephyr vnc4server -f
    - pip install pyvirtualdisplay -f
    # optional
    - apt-get install python-pil scrot -f
    - pip install pyscreenshot -f
    - npm install
    - npm run cytest
  artifacts:
    paths:
      - code/servelog.txt
    expire_in: 1 week

build_code:
  stage: build
  script:
    - ls
    - cd code
    - npm install
    - npm run build
