image: cypress/base:10

stages:
  - test
  - build

cache:
  paths:
    - node_modules/

run_cypress:
  stage: test
  script:
    - cd code
    - npm install
    - npm run cytest
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - /builds/weicker/varg/code/cypress/screenshots
    - /builds/weicker/varg/code/cypress/videos
    - /builds/weicker/varg/code/servelog.txt

build_code:
  stage: build
  script:
    - ls
    - cd code
    - npm install
    - npm run build
