# image: node:12.14.1
image: cypress/base:10

stages:
  - test
  - build

cache:
  paths:
    - node_modules/

# install_dependencies:
#   stage: .pre
#   script:
#     - cd code
#     - npm install

run_cypress:
  stage: test
  script:
    - cd code
    # - apt-get -y install xvfb
    # - apt update
    # # - apt upgrade
    # - apt-get install python-pip -qq | tee log.txt
    # - apt-get install xvfb xserver-xephyr vnc4server -qq | tee log.txt
    # - pip install pyvirtualdisplay | tee log.txt
    # # optional
    # - apt-get install python-pil scrot -qq | tee log.txt
    # - pip install pyscreenshot | tee log.txt
    - npm install
    - npm run cytest
    artifacts:
      expire_in: 1 week
      when: always
      paths:
      - /builds/weicker/varg/code/cypress/screenshots
      - /builds/weicker/varg/code/cypress/videos
      - /builds/weicker/varg/code/servelog.txt
      - /builds/weicker/varg/code/log.txt
      reports:
        junit:
          - results/TEST-*.xml

  artifacts:
    paths:
      - code/servelog.txt
      - code/log.txt
    expire_in: 1 week

build_code:
  stage: build
  script:
    - ls
    - cd code
    - npm install
    - npm run build
