version: "3"
services:

  node:
    image: node:8
    links: -"database"

  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_USER=varg
      - MYSQL_PASSWORD=VarG2020
      - MYSQL_DATABASE=vargdb
      - MYSQL_ROOT_PASSWORD=geheim
    volumes:
      - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always